### ISSUE TITLE
Choose a state management

### ISSUE THREAD

**Issue by lucasmontano** [lucasmontano/learn-tech#4]

**Comment by gilvanhenriqued** [comment]
I think that is a good idea to use MobX with Flutter Modular to state management. This can help the code moduralization... :D

**Comment by luizeduardotj** [comment]
A simple list of possibilities:
 - flutter_bloc
 - cubit
 - mobx
 - get
 - Bloc with rxdart
 - ValueNotifier

**Comment by gabrielbarreto030** [comment]
MobX is simple and very current

**Comment by VictorVasconcellos42** [comment]
I Think **MobX** is better for the project and simple to understand!

**Comment by LuizEduu** [comment]
MobX is simple, very powerful and has a good amount of materials available for research.

**Comment by nitoba** [comment]
Mobx is a powerful way to do state management and simple to use due your concepts easy to understand and untill who never was working with flutter get understand

**Comment by evandrmb** [comment]
Mobx it's powerful and simple.

**Comment by rodrigorafaeldamaceno** [comment]
Mobx, simple and solve the problem.

**Comment by lucasvps** [comment]
Mobx with Modular, it will solve the problem about dependency injection and also the state management.

**Comment by ArthurFleischman** [comment]
mobx is the best one.

**Comment by lucasmontano** [comment]
as we can all agree, let's go with mobx :D
