### ISSUE TITLE
Suggestion: Choose a dependency injection system

### ISSUE THREAD

**Issue by luizeduardotj** [lucasmontano/learn-tech#6]
May be interesting to choose a dependency injection system for providing the state management classes for us

**Comment by nitoba** [comment]
Flutter modular is a good mode to do dependency injection but can to be a little bit more advanced. The Provider can to be more easy to use but there are the trouble of bind of context for get and inject your dependencies

**Comment by luizeduardotj** [comment]
> Flutter modular is a good mode to do dependency injection but can to be a little bit more advanced. The Provider can to be more easy to use but there are the trouble of bind of context for get and inject your dependencies 

Yep. Provider can help us. Or we can use the [Riverpod](https://riverpod.dev/)
, another way to manage our dependence injector system. The Riverpod was created by Remi Rousselet, the same creator of Provider. How he say: "Provider, without it's limitations"

**Comment by nitoba** [comment]
> > Flutter modular is a good mode to do dependency injection but can to be a little bit more advanced. The Provider can to be more easy to use but there are the trouble of bind of context for get and inject your dependencies
> 
> Yep. Provider can help us. Or we can use the [Riverpod](https://riverpod.dev/)
> , another way to manage our dependence injector system. The Riverpod was created by Remi Rousselet, the same creator of Provider. How he say: "Provider, without it's limitations"

This package I not knows, in question of dependency injection for read and inject your dependencies look likes cool and with hooks reduce well the boiler plate but as state management I prefer use Mobx

**Comment by luizeduardotj** [comment]
> This package I not knows, in question of dependency injection for read and inject your dependencies look likes cool and with hooks reduce well the boiler plate but as state management I prefer use Mobx

It works with any state management

**Comment by evandrmb** [comment]
GetIt is another option for dependency injection. In my personal opnion it's simpler than provider and modular.  I have a bit of experience with Modular and it's a great option too!

**Comment by rodrigorafaeldamaceno** [comment]
i think provider is a good dependency injection, together with mobx is a good option to the project. Very easy and solve the problem.

**Comment by ArthurFleischman** [comment]
i think flutter modular from fluterando is pretty good, it combines singletons and dependency injection in the same package.
package link: https://pub.dev/packages/flutter_modular

**Comment by rodrigorafaeldamaceno** [comment]
> i think flutter modular from fluterando is pretty good, it combines singletons and dependency injection in the same package.
> package link: https://pub.dev/packages/flutter_modular

I disagree, the modular ends up being more complex in the beginning, and since the idea is to speed up the project, it is not ideal.

**Comment by ArthurFleischman** [comment]
> > i think flutter modular from fluterando is pretty good, it combines singletons and dependency injection in the same package.
> > package link: https://pub.dev/packages/flutter_modular
> 
> I disagree, the modular ends up being more complex in the beginning, and since the idea is to speed up the project, it is not ideal.
> 

So, give me an alternative please....

**Comment by rodrigorafaeldamaceno** [comment]
> > > i think flutter modular from fluterando is pretty good, it combines singletons and dependency injection in the same package.
> > > package link: https://pub.dev/packages/flutter_modular
> > 
> > 
> > I disagree, the modular ends up being more complex in the beginning, and since the idea is to speed up the project, it is not ideal.
> 
> So, give me an alternative please....

I mentioned above that mobx and provider are a good option for the project

**Comment by ArthurFleischman** [comment]
> > > > i think flutter modular from fluterando is pretty good, it combines singletons and dependency injection in the same package.
> > > > package link: https://pub.dev/packages/flutter_modular
> > > 
> > > 
> > > I disagree, the modular ends up being more complex in the beginning, and since the idea is to speed up the project, it is not ideal.
> > 
> > So, give me an alternative please....
> 
> I mentioned above that mobx and provider are a good option for the project
> 

The problem with provider, its because the same is "hostage of the context", if we need to retrive data from a tab view controller... we are screwed....

**Comment by rodrigorafaeldamaceno** [comment]
> > > > > i think flutter modular from fluterando is pretty good, it combines singletons and dependency injection in the same package.
> > > > > package link: https://pub.dev/packages/flutter_modular
> > > > 
> > > > 
> > > > I disagree, the modular ends up being more complex in the beginning, and since the idea is to speed up the project, it is not ideal.
> > > 
> > > 
> > > So, give me an alternative please....
> > 
> > 
> > I mentioned above that mobx and provider are a good option for the project
> 
> The problem with provider, its because the same is "hostage of the context", if we need to retrive data from a tab view controller... we are screwed....

I don't see so much problem, it depends a lot on the implementation, modular adds an unnecessary complexity for those who are starting.

**Comment by ArthurFleischman** [comment]
> > > > > > i think flutter modular from fluterando is pretty good, it combines singletons and dependency injection in the same package.
> > > > > > package link: https://pub.dev/packages/flutter_modular
> > > > > 
> > > > > 
> > > > > I disagree, the modular ends up being more complex in the beginning, and since the idea is to speed up the project, it is not ideal.
> > > > 
> > > > 
> > > > So, give me an alternative please....
> > > 
> > > 
> > > I mentioned above that mobx and provider are a good option for the project
> > 
> > 
> > The problem with provider, its because the same is "hostage of the context", if we need to retrive data from a tab view controller... we are screwed....
> 
> I don't see so much problem, it depends a lot on the implementation, modular adds an unnecessary complexity for those who are starting.

it's true..... let's go with provider ...
